name: voidlord
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.1+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  get: ^4.6.6
  cached_network_image: ^3.4.1
  logger: ^2.5.0
  shimmer: ^3.0.0
  file_picker: ^8.3.3
  archive: ^4.0.2
  webview_flutter: ^4.10.0
  path_provider: ^2.1.5
  crypto: ^3.0.6
  xml: ^6.5.0
  path: ^1.9.0
  html: ^0.15.5
  ruby_text: ^3.0.3
  csslib: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
