name: voidlord
description: "voidlord app"
publish_to: 'none' 
version: 1.0.10+debug

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  get: ^4.6.6
  cached_network_image: ^3.4.1
  logger: ^2.5.0
  shimmer: ^3.0.0
  file_picker: ^8.3.3
  archive: ^4.0.2
  path_provider: ^2.1.5
  crypto: ^3.0.6
  xml: ^6.5.0
  path: ^1.9.0
  html: ^0.15.6
  ruby_text: ^3.0.3
  csslib: ^1.0.2
  cached_memory_image: ^1.5.0
  msgpack_dart: ^1.0.1
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  floor: ^1.5.0
  intl: ^0.20.2
  photo_view: ^0.15.0
  flutter_svg: ^2.1.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  floor_generator: ^1.5.0

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
